//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public Device()
        {
            this.Device2Module = new HashSet<Device2Module>();
        }
    
        public int Id { get; set; }
        public string UDID { get; set; }
    
        public virtual ICollection<Device2Module> Device2Module { get; set; }
    }
}
