//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device2Module
    {
        public int Id { get; set; }
        public Nullable<int> DeviceId { get; set; }
        public int ModuleId { get; set; }
        public string ActivationCode { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Module Module { get; set; }
    }
}
