//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.Device2Module = new HashSet<Device2Module>();
            this.Module2Tag = new HashSet<Module2Tag>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int SoldNumber { get; set; }
        public string UserId { get; set; }
        public string NativeLang { get; set; }
        public string ForeignLang { get; set; }
        public string Text { get; set; }
        public bool Locked { get; set; }
        public string PaypalButtonId { get; set; }
        public string ImageFileName { get; set; }
        public string NewNativeLangCode { get; set; }
        public string NewNativeLangName { get; set; }
        public string NewForeignLangCode { get; set; }
        public string NewForeignLangName { get; set; }
        public string TransUILabels { get; set; }
        public string ForeignName { get; set; }
        public string ForeignDescription { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Device2Module> Device2Module { get; set; }
        public virtual ICollection<Module2Tag> Module2Tag { get; set; }
    }
}
